### ISSUE TITLE
Plan for 2.0.0

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/antsibull-docs#104]
@gotmax23 what do you think about the following:

1. Get a 1.x.y version done for use in ansible-core 2.15.
2. Once that's done (basically once ansible-core 2.15 is in feature freeze), create a stable-1 branch and prepare 2.0.0 (drop Python < 3.9 etc.).
3. Release 2.0.0.

**Comment by felixfontein** [comment]
Actually for 2.0.0 I would consider adding antsibull-changelog as a dependency to implement #31.

**Comment by gotmax23** [comment]
Sounds reasonable to me. As part of this change, I'd like to get rid of the antsibull_docs code that relies on `sh` and `antsibull_core.venv`.

**Comment by felixfontein** [comment]
I agree on `sh`, but `antsibull_core.venv` should be replaced by something in antsibull-core that abstracts away venvs vs. no venvs. But that depends somewhat on how https://github.com/ansible-community/antsibull-core/issues/34 develops from my POV.

**Comment by felixfontein** [comment]
I created a stable-1 branch: https://github.com/ansible-community/antsibull-docs/tree/stable-1

**Comment by felixfontein** [comment]
I started a nox+hatchling PR in #115.

**Comment by felixfontein** [comment]
And poetry is gone :tada:

Other things to do:
- [ ] get rid of sh
- [ ] depend on antsibull-changelog and implement (some form of) #31
- [ ] support using `FakeVenvRunner` for `stable` and `devel` subcommands (allows to improve Ansible/ansible-core docs build and the corresponding sanity tests)

**Comment by felixfontein** [comment]
Maybe also:
- [ ] drop support for ansible-core < 2.13. This makes docs parsing a lot easier, since there is only one method left.

**Comment by felixfontein** [comment]
- [ ] remove automatic unflatmappting for *everything*. (But still allow to use it for some collections.)

**Comment by felixfontein** [comment]
I think that once #145 is merged we can create a 2.0.0a1 pre-release (and soon a release). WDYT @gotmax23?

**Comment by gotmax23** [comment]
> depend on antsibull-changelog and implement (some form of) https://github.com/ansible-community/antsibull-docs/issues/31

was listed in https://github.com/ansible-community/antsibull-docs/issues/104#issuecomment-1500982148. Do you still want to implement that for 2.0.0? Otherwise, I think we're good to go.

**Comment by felixfontein** [comment]
I think we can also do that for 2.x.0; adding a new dependency shouldn't be a problem.

**Comment by felixfontein** [comment]
[2.0.0a1 has been released](https://github.com/ansible-community/antsibull-docs/releases/tag/2.0.0a1)

**Comment by gotmax23** [comment]
> [2.0.0a1 has been released](https://github.com/ansible-community/antsibull-docs/releases/tag/2.0.0a1)

🎉! Do you want to announce it on the Bullhorn?

**Comment by felixfontein** [comment]
2.0.0 is out! :tada:
