### ISSUE TITLE
Clarification on "expanded collections" and support for collections on disk

### ISSUE THREAD

**Issue by briantist** [ansible-community/antsibull-docs#211]
When running `antsibull-docs collection --help` it says this about the collection list:

```
positional arguments:
  collections           One or more collections to document. If the names are directories on disk, they will be parsed as
                        expanded collections. Otherwise, if they could be collection names, they will be downloaded from galaxy.
```

I thought this might mean that you could give path names (where collections already exist) and that it would use those, retrieving the collection name from the `galaxy.yml` or `MANIFEST.json` in that path. But it does not seem to work that way, since it ends up trying to download the path as though it's a collection name.

> antsibull_core.galaxy.NoSuchCollection: No collection found at: https://galaxy.ansible.com/api/v2/collections/tmp/adocs/ansible_collections/namespace/collection/versions/

When I look through the code, it doesn't seem like there is any code supporting reading such a collection from disk, so I'm wondering if that note about the names being "directories on disk" refers to old functionality, or maybe it means something else entirely?

If I try to do the same with `--use-current`, the command "succeeds" but doesn't actually build anything except an empty `index.rst` and `environment_variables.rst`, presumably because it couldn't find collections with those weird names (there's no console output at all in this case, and `--fail-on-error` also didn't change that).

---

### Why I was interested in this

I'm going to build an internal docsite, and so I need some way to know which collections to include. 
Some will be installed via git rather than through the galaxy API protocol.

To organize this, I thought it might be nice to simply use a `requirements.yml` with the git sources to serve as my canonical collection list. If I install them in a separate step, then I can use `--use-current` to avoid auto-install, but then I need to supply the collection names themselves to `antsibull-docs` again.

I thought I could avoid it altogether with a workflow that looks something like:

```
ansible-galaxy collection install -r requirements.yml -p /tmp/adocs
antsibull-docs collection /tmp/adocs/ansible_collections/namespace/*
```

I wasn't too keen on parsing the YAML myself just to pass the names, especially since for git sources the `name:`  field is the git URL so I don't necessarily have a name to pass without storing it separately.

### Suggestions

For now I will just have to keep a separate list of collection names probably, but I can imagine two possible enhancements:
1. You're already attempting to install collections from the list of names, maybe have a mode where it takes a `requirements.yml` file instead and can install using that config, and then no names need to be passed.
2. Implement/restore the ability to pass directories on disk that already refer to collections.

If you think either of those are a possibility I can split them out to separate issues, curious what you think.

**Comment by felixfontein** [comment]
Hmm, I don't think passing directory names was ever supported. Passing paths to tarballs might be supported without `--use-current`, and maybe that was meant, but this is probably something that was written when antsibull was originally created and potentially just never implemented.

In any case, with `--use-current`, only collection names can be supplied. I guess we need to improve validation for that.

**Comment by briantist** [comment]
Looking at the code, I think the behavior would be the same whether the paths passed are tarballs or directories, it just has no detection for that at all. If `--use-current` is not set the first thing it does is try to retrieve collections:
https://github.com/ansible-community/antsibull-docs/blob/main/src/antsibull_docs/cli/doc_commands/collection.py#L134

And the `retrieve` function does that over HTTP pretty much right away without checking for dirs/tarballs:
https://github.com/ansible-community/antsibull-docs/blob/main/src/antsibull_docs/cli/doc_commands/collection.py#L79

That's fine though, good to have understanding of that.

---

Any thoughts on the idea of having the retrieval path (not using `--use-current`) accept a `requirements.yml`?

**Comment by felixfontein** [comment]
> Any thoughts on the idea of having the retrieval path (not using `--use-current`) accept a `requirements.yml`?

The problem with `requirements.yml` is that it can contain a lot more syntaxes than just "here's a collection name and a version" (https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html#install-multiple-collections-with-a-requirements-file). What we could do is simply call `ansible-galaxy collection install -r /path/to/requirements.yml`.

> I thought I could avoid it altogether with a workflow that looks something like:
> 
> ```
> ansible-galaxy collection install -r requirements.yml -p /tmp/adocs
> antsibull-docs collection /tmp/adocs/ansible_collections/namespace/*
> ```

You can almost do this with the `current` subcommand:
```
ansible-galaxy collection install -r requirements.yml -p /tmp/adocs
antsibull-docs current --collection-dir /tmp/adocs/
```
The downside is that this includes ansible.builtin.

But I guess we could add a flag that stops including ansible.builtin.

**Comment by felixfontein** [comment]
#214 does some cleanup, like no longer claiming things that don't work, and adding better validation.

**Comment by felixfontein** [comment]
#215 adds `--exclude-ansible-builtin` to the `current` subcommand. With that,
```
ansible-galaxy collection install -r requirements.yml -p /tmp/adocs
antsibull-docs current --collection-dir /tmp/adocs/ --exclude-ansible-builtin
```
should do what you want.

(There's one case that this doesn't cover: if collections in requirements.yml have other collection dependencies, these will be installed as well, and the docsite will also contain these.)

**Comment by briantist** [comment]
> #215 adds `--exclude-ansible-builtin` to the `current` subcommand. With that,
> 
> ```
> ansible-galaxy collection install -r requirements.yml -p /tmp/adocs
> antsibull-docs current --collection-dir /tmp/adocs/ --exclude-ansible-builtin
> ```
> 
> should do what you want.
> 
> (There's one case that this doesn't cover: if collections in requirements.yml have other collection dependencies, these will be installed as well, and the docsite will also contain these.)

This is great! That workflow is what I'm currently using (but with `antsibull-docs collection` and a separate list of collections in a txt file that I expand on the command line), so changing to `antsibull-docs current` should be a nice improvement and let me eliminate the txt file.

I'm already adding `--no-deps` to `ansible-galaxy` and that combined with installing to a fresh `/tmp` location should prevent me from having any unwanted collections in the mix.

Thanks so much @felixfontein ! 🙌 

With those two PRs, I think we can call this closed!

**Comment by felixfontein** [comment]
> I'm already adding `--no-deps` to `ansible-galaxy` and that combined with installing to a fresh `/tmp` location should prevent me from having any unwanted collections in the mix.

Be warned that `--no-deps` will cause you pain if you need docs fragments from the dependencies ;-)

**Comment by briantist** [comment]
> Be warned that `--no-deps` will cause you pain if you need docs fragments from the dependencies ;-)

💡 that's very true, I totally forgot about that... I don't _think_ any of the collections in this internal docsite will need doc frags from any collection that isn't also explicitly going to be in the docsite, but it's definitely something I'll need to remember..

In that case the way I'm doing it now with the `collection` subcommand and a txt file with collection names would actually account for that case, as long as I remove `--no-deps` or leave instructions that docs dependencies need to be added to `requirements.yml` and left out of the txt file.
