### ISSUE TITLE
Collection note should indicate that further dependencies may be required.

### ISSUE THREAD

**Issue by samccann** [ansible-community/antsibull-docs#23]
Can't transfer the issue from https://github.com/ansible/ansible/issues/74195 so doing the copy-pasta:

I am a contributor to the ansible.azcollection project. In order for those modules to execute, many azure specific packages must be installed via pip.
At the top of all of the online documentation for modules, there is a "Note" banner on installing the collection, example
https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_storageaccount_module.html
That banner is added to every module's doc in all of the collections in that doc site.

The problem we're running into is that newer users read that banner and believe that it satisfies all dependencies by doing the 'ansible-galaxy collection install ${collection} ' . Could some additional text be added to indicate that there may be further dependencies, and that they should click on the collection link to see the collection specific docs?

I would attempt a PR myself, but I have no idea how the docs are composed or where the banner message is being pulled from. If this is not the correct repo to report the issue against, let me know and I'll resubmit there.

**Comment by felixfontein** [comment]
See #24 for a possible way to do this. Basically if there is a requirements section for the plugin/module, mention that additional requirements are needed and link to that section.
