### ISSUE TITLE
Removed plugins are not removed from disc

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/antsibull-docs#303]
Removed plugins are not removed from disc when running `antsibull-docs collection-plugins` and that is a problematic because it leads to bugs: when someone removes or renames a plugin, they might forget to update the documentation.

As other docs might be inside the same folder, we should check of the "Generated by" marker before removing the files.

**Comment by felixfontein** [comment]
This is not a bug, but intended design. If you want files to be deleted, you have to do that yourself. For example you can create a wrapper script, see the script created by `antsibull-docs sphinx-init`.
