### ISSUE TITLE
Allow to disable inserting version numbers into generated documentation

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/antsibull-docs#304]
We need an option for not mentioning the version number, otherwise any king of update in the version would require regenerating the docs, creating too much churn.

This affects ability to track generated documentation with git.

Found this with antsibull-docs==2.12.0

**Comment by felixfontein** [comment]
This is not a bug, but a feature request.

**Comment by felixfontein** [comment]
Also, **which** version(s) are you talking about? The collecftion version? The antsibull-docs version?
