### ISSUE TITLE
Generated docs do not pass most basic trailing-whitespace and end-of-file-fixer pre-commit hooks

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/antsibull-docs#305]
Generated docs do not pass most basic trailing-whitespace and end-of-file-fixer pre-commit hooks.

We need to ensure that generated RST files:

- [ ] do not have trailing whitespace
- [ ] do not have missing or extra newlines at the end of file

This will ensure that generated files do not need to be excluded from our normal linters.

**Comment by felixfontein** [comment]
This again is a feature request, not a bug. Please don't assign labels here and let the maintainers triage new issues. Thanks.
