### ISSUE TITLE
Use of rsync inside generated build.sh prevents usage with readthedocs

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/antsibull-docs#306]
To build with RTD, we will need to make use of custom build commands, aka `build.commands` feature, one that is highly promoted by them (aiming to become the default very soon).

Still, this feature comes with one major downside, losing ability to use `apt_packages` (and sudo is not available either).

All VM images provided by RTD do not have rsync installed and they [do not want to install it](https://github.com/readthedocs/readthedocs.org/issues/11219).

This means that in its current form antsibull-docs cannot be integration with RTD, which is currently the most common system that allows to test pull-requests changes made to documentation.

I do think that we might need to find a way to make rsync optional in `build.sh`, falling back to a plain old copy instead.

References:

- https://github.com/readthedocs/readthedocs.org/issues/11219
- https://github.com/readthedocs/readthedocs.org/issues/9599
- https://github.com/ansible/event-driven-ansible/pull/276

**Comment by felixfontein** [comment]
This again is **not a bug**, but an enhancement.

**Comment by ssbarnea** [comment]
@felixfontein We could argue four hours about what makes an issue a feature, bug or fug but that is better over a glass of beer. It becomes funny when a design flaw becomes a feature, just because the original design missed to cover that aspect. 🍻

**Comment by felixfontein** [comment]
@ssbarnea it's pretty simple. If a feature works as designed, it's not a bug, but a feature / enhancement request. The feature here works as designed. So it's not a bug.
