### ISSUE TITLE
2.13 possible regression

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/antsibull-docs#316]
The new release 2.13 seems to be causing some problems and I am seeing something quite unexpected:
```
Theme error:
An error happened in rendering the page activation_info_module.
Reason: UndefinedError("'style' is undefined")
```

PS. I am not 100% sure is this and not another docs dependency as this happened while I was trying to add some constraints to testing in order to control the updates.

**Comment by felixfontein** [comment]
This is not an error reported by antsibull-docs, so you'll need to provide more information.

**Comment by felixfontein** [comment]
Searching the web for the error message gives for example https://github.com/readthedocs/sphinx_rtd_theme/issues/1465, which indicates that this is a problem with a Sphinx theme, and not related to antsibull-docs at all. I'm therefore closing this issue.
