### ISSUE TITLE
Markdown unordered list in this repo's docs is rendered incorrectly

### ISSUE THREAD

**Issue by kpfleming** [ansible-community/antsibull-docs#364]
The content in `collection-docs.md` is rendered properly when GitHub's 'preview' mode is used, but not when published on ansible.readthedocs.io. Specifically:

![image](https://github.com/user-attachments/assets/3d7d58f3-7508-4739-949f-6df40e1e515b)

Neiher `--skip-rstcheck` or `--disallow-semantic-markup` appear as list items.

**Comment by felixfontein** [comment]
Thanks for reporting this! #365 fixes this.
