### ISSUE TITLE
role examples section is wrong heading level

### ISSUE THREAD

**Issue by akira6592** [ansible-community/antsibull-docs#366]
The `Example` head level must be the same as the `Parameters`.

<img width="744" alt="image" src="https://github.com/user-attachments/assets/b242294e-a98a-40c0-9e5d-ede37a1cc90f" />

https://github.com/ansible-community/antsibull-docs/blob/1003bcbabd4aaa88d4cc0d444773a54e98a5b822/src/antsibull_docs/data/docsite/ansible-docsite/role.rst.j2#L196-L197

**Comment by felixfontein** [comment]
Thanks for reporting this! #367 should fix it.

**Comment by akira6592** [comment]
Thank you for submitting the PR quickly!
