### ISSUE TITLE
Display shortdescription for plugins listed in See Also section

### ISSUE THREAD

**Issue by samccann** [ansible-community/antsibull-docs#64]
Currenty, the See Also lists related plugins on a plugin docs page, but it doesn't display the short description for that plugin:

![image](https://user-images.githubusercontent.com/30267855/200857215-6243011d-c71d-474a-9cc8-22c3056833a7.png)

Would be great if we could replace that boilerplate text with the actual plugin short description.

**Comment by felixfontein** [comment]
Implemented in #74.
