### ISSUE TITLE
Building the ansible documentation always times out

### ISSUE THREAD

**Issue by dilyanpalauzov** [ansible-community/antsibull-docs#9]
As described at https://github.com/ansible/ansible/issues/78002.

**Comment by samccann** [comment]
@dilyanpalauzov sorry for the misunderstanding with the request to move this issue. This isn't a bug, it's a system requirement on how much memory is needed to build the full docs. I'll leave this open for a bit to see if you had other comments but I don't see this as something that will be fixed per se.

**Comment by felixfontein** [comment]
That phase of the docs build shouldn't need *that* much memory (the later phases will though, once Sphinx is started). We should definitely have better error handling for timeouts. What might help is reducing the amount of parallel downloads. You can do that by creating an antsibull config file (~/.antsibull.cfg) with `thread_max = 2` or even `thread_max = 1` (see https://github.com/ansible-community/antsibull-core/blob/main/antsibull.cfg for all options).

**Comment by dilyanpalauzov** [comment]
I created a 16GB swap file and then building the documentation completed.

**Comment by samccann** [comment]
Great thanks for confirming. Closing the issue now.
