### ISSUE TITLE
Allow to declare collections as unmaintained, ... for Ansible docsite builds

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/antsibull-docs#93]
That should use https://github.com/ansible-community/ansible-build-data/blob/main/8/collection-meta.yaml somehow.

**Comment by mariolenz** [comment]
I'm not sure if this is really doable, but if we consider a collection unmaintained we will remove it from the Ansible community package. Maybe we could generate the changelog entry automatically from `collection-meta.yml` so we don't have to define a collection as unmaintained in two places?

Just an idea.

**Comment by felixfontein** [comment]
This is mainly for the time between when we decide to remove it and when it's actually removed. In that time, showing our intention on the docsite is a good idea IMO.

**Comment by felixfontein** [comment]
I created https://github.com/ansible-community/ansible-build-data/pull/450 as a way how the format could look like in `collection-meta.yml`.

**Comment by felixfontein** [comment]
Automatically generated changelog entries would be possible as well (I just pushed a commit that has more information needed for it), but there are more special cases, for example `Since they've also announced to not support ansible-core 2.18, it will be removed from Ansible 11 if no one starts maintaining it again before Ansible 11` for frr.frr and openvswitch.openvswitch.

**Comment by felixfontein** [comment]
Both antsibull and antsibull-docs should read / process it. I guess it makes more sense to move it to antsibull-core then.

I'd prefer to first merge https://github.com/ansible-community/antsibull/pull/617 with the schema in antsibull itself though, and then create a PR to move the schema to antsibull-core. Does that sound acceptable? That's easier than coordinating two PRs in both repos (espectially w.r.t. CI).

**Comment by gotmax23** [comment]
You wrote the code so whatever way you prefer to land it is fine with me :). I left some feedback on the antsibull PR.

**Comment by felixfontein** [comment]
Ref: https://github.com/ansible-community/antsibull-core/pull/168
Ref: https://github.com/ansible-community/antsibull/pull/620

**Comment by felixfontein** [comment]
I've implemented this in #330. That PR shows deprecation markers in collection lists and deprecation notes on plugin/role pages and the collection index pages of collections that will be removed.
